### ISSUE TITLE
GF Kernel character set?

### ISSUE THREAD

**Issue by davelab6** [razvanm/computer-modern-classic#1]
If the kernel set (from https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin) can be supported, then these are 100% good to go live in GF without delay. 

If not, I'm happy to support the project in any way to get them there :)

**Comment by razvanm** [comment]
I believe the there 16 missing glyphs in Regular and 25 in Italic to complete the GF Kernel. I'll work on adding them.

Regular:

1. 0x0022 QUOTATION MARK
2. 0x0027 APOSTROPHE
3. 0x005C REVERSE SOLIDUS
4. 0x005E CIRCUMFLEX ACCENT
5. 0x005F LOW LINE
6. 0x007C VERTICAL LINE
7. 0x007E TILDE
8. 0x00A2 CENT SIGN
9. 0x00A3 POUND SIGN
10. 0x00A5 YEN SIGN
11. 0x00A9 COPYRIGHT SIGN
12. 0x00AE REGISTERED SIGN
13. 0x00B0 DEGREE SIGN
14. 0x2026 HORIZONTAL ELLIPSIS
15. 0x20AC EURO SIGN
16. 0x2122 TRADE MARK SIGN

Italic:

1. 0x0022 QUOTATION MARK
2. 0x0027 APOSTROPHE
3. 0x003C LESS-THAN SIGN
4. 0x003E GREATER-THAN SIGN
5. 0x005C REVERSE SOLIDUS
6. 0x005E CIRCUMFLEX ACCENT
7. 0x005F LOW LINE
8. 0x007B LEFT CURLY BRACKET
9. 0x007C VERTICAL LINE
10. 0x007D RIGHT CURLY BRACKET
11. 0x007E TILDE
12. 0x00A2 CENT SIGN
13. 0x00A3 POUND SIGN
14. 0x00A5 YEN SIGN
15. 0x00A9 COPYRIGHT SIGN
16. 0x00AE REGISTERED SIGN
17. 0x00B0 DEGREE SIGN
18. 0x00B7 MIDDLE DOT
19. 0x00D7 MULTIPLICATION SIGN
20. 0x00F7 DIVISION SIGN
21. 0x2022 BULLET
22. 0x2026 HORIZONTAL ELLIPSIS
23. 0x20AC EURO SIGN
24. 0x2122 TRADE MARK SIGN
25. 0x2212 MINUS SIGN

**Comment by razvanm** [comment]
Quick update: the Computer Modern Classic has now support not only for GF Latin Kernel but also GF Latin Core. 🎉

The only failure the FontBakery shows is for the experimental com.google.fonts/check/glyphsets/shape_languages check added in Nov 2023. I'm looking into that in issue #22.

Thanks @davelab6 for the early encouragement! 🤗
